apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gleb-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/1Ghost19/final-task.git
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: gleb-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
