apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zgh-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/Herman7883/Final_Task_devops.git
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: zgh-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true