apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lubo-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/MaksimLyubomsky/Lub_final_task.git
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: lubo-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
