apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmelekhov-sampleapp
spec:
  project: default
  source:
    repoURL: https://github.com/Mikys997/FInal-taskdevops.git
    targetRevision: main
    path: deployment/kustomize/overlays/common
  destination:
    name: in-cluster
    namespace: nmelekhov-sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
